module.exports = function sync_exception () {
    throw new Error('Error thrown')
}